### PR TITLE
Fix client bugs

### PR DESCRIPTION
**Pull request by mixmasala**
this PR fixes a few different issues I discovered while trying to figure out why clients using this library would puke after a new PKI document.

### CODE REVIEW

**Comment by mixmasala** [comment]
I *think* the fetchInterval is correct but please check this.

**Comment by david415** [comment]
i think your avoid integer division commit is wrong... i've attempted to fix this polling interval situation in another pull-request here: https://github.com/katzenpost/client/pull/72

**Comment by david415** [comment]
> I _think_ the fetchInterval is correct but please check this.

It's not correct. See my other pull request for the fix: https://github.com/katzenpost/client/pull/72

**Comment by david415** [comment]
hmm maybe i should rebase or cherry pick your commits onto my new pull request or do you want to do it? @mixmasala ok i'm closing this PR now.

**Pull request closed without merging**
